### ISSUE TITLE
Need More Information About Setup

### ISSUE THREAD

**Issue by Sunhui26yeah** [ASSERT-KTH/collector-sahab#430]
Hi Aman,

I recently attempted to run your project on my own, but I encountered some issues, particularly with the execution part. I’m hoping you could provide some clarification. Should this project be run on GitHub workflows, or is it meant to be executed locally on our own computers?

I attempted to run this project on my own computer, but I ran into some problems. I’ll list my steps below and hope you can point out where I might have gone wrong.

I installed gawk.
I installed chromium-chromedriver.
I packaged the project by "mvn package DskipTests", and it completed successfully.
I ran mvn test, but encountered a problem with a "Surefire version conflict." I skipped this step since the tests are optional.
I have my own target repository called "TestMVN" on my GitHub account.
I ran the project with the following command:

"java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar \
    -p /home/\<my user name\>/IdeaProjects/TestMVN \
    -l 2ef8d41 \
    -r 3e5b73d \
    -c src/main/java/org/example/Main.java \
    --slug Sunhui26yeah/TestMVN"

This resulted in the following error log:
![image](https://github.com/user-attachments/assets/ec67cb10-506f-415e-ad3b-175b3512307c)

From my understanding:

-p needs to be the path to the target project on my computer.
-l needs to be the old commit version of my target Maven project.
-r needs to be the new commit version of my target Maven project.
-c needs to be the relative path to the class file in my target Maven project.
--slug should be "Sunhui26yeah/TestMVN," which corresponds to my GitHub repository.

![image](https://github.com/user-attachments/assets/3d2b4d8f-b143-46f4-97c7-d25962c1f9e1)
 
Could you please point out where I might be going wrong? I would greatly appreciate your help!

**Comment by Sunhui26yeah** [comment]
Update:

I have tried the "iotdb" with commit "a3559e5" and "6d2a1cf" you specified in your paper with the following command:

"java -jar main/target/collector-sahab-1.0-SNAPSHOT-jar-with-dependencies.jar
-p /home/<my user name>/IdeaProjects/iotdb
-l a3559e5
-r 6d2a1cf
-c server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
--slug apache/iotdb"

I notice that the project find the breakpoints as expected.
![image](https://github.com/user-attachments/assets/69daccd7-00bb-45cf-b63f-587c8b1ffa8c)


However, I find the 0.json file is empty.
![image](https://github.com/user-attachments/assets/2d2c7141-7ae2-4719-8239-6150a0f54cb5)

And the generated html file cannot be opened.

**Comment by algomaster99** [comment]
Hi @Sunhui26yeah ! Thank you for taking an interest in our project :D

I haven't tried running your project, but I am trying to reproduce the report for `iotdb`. It seems that `0.json` is empty (which means there is no trace) because `org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext` is never executed as `mvn test` fails because our javaagent fails as shown here.

![image](https://github.com/user-attachments/assets/a3f75539-6391-45d5-a2e1-ab3503d540d0)

The problem seems to be because of some API in fasterxml which is strange as tests on our CI pass and it also has an integration test.
My suggestion would be run it again with the latest release - https://github.com/ASSERT-KTH/collector-sahab/releases/tag/v0.5.3. The version on `main` has automated dependency updates only. I am giving it a go with the latest release and will get back to you if I find something.

**Comment by Sunhui26yeah** [comment]
Hi Aman, 

Thank you so much for your response! Yes, collector_sahab is a significant improvement in analyzing code run-time diffs. It really interests me a lot! I will try the release v0.5.3. Could you please let me know the input parameters (including the test case) where a pop-up page like below will appear?
![image](https://github.com/user-attachments/assets/49232329-158c-41b5-8d7d-df4be3056827)

I also wonder if my understanding of the input parameters is correct. For example, if we take iotdb as an example,
"java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar
-p /home/hsun26/IdeaProjects/iotdb \\    _**the path to iotdb project on my computer**_
-l a3559e5 \\
-r 6d2a1cf \\
-c server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java \\
--slug apache/iotdb"

I have tried my test maven project, it finally generated the html but without the pop-up shows the difference as expected.
![987c6d4fa510d9d4b4e88cffe21f755](https://github.com/user-attachments/assets/0527b409-dca2-4b8d-865e-13d9b6693d89)
I will try the latest release! Thanks again!

**Comment by algomaster99** [comment]
>  Should this project be run on GitHub workflows, or is it meant to be executed locally on our own computers?

The ideal goal is to run in the CI using GitHub actions so we have access to GitHub repository. Right now, we use selenium to get the GitHub UI and then augment it. The latter was done for the sake of time. Since we were also just prototyping, we did not really polish the implementation :sweat_smile: 

> Yes, collector_sahab is a significant improvement in analyzing code run-time diffs.

Thank you so much!

> I also wonder if my understanding of the input parameters is correct. For example, if we take iotdb as an example,

Yes, your understanding is correct and the command you have provided is correct.

I further investigated the error. It seems that `fasterxml` in `iotdb` was conflicting with the one in `collector-sahab`. [Here](https://github.com/user-attachments/files/16856134/prevent-overloading-fasterxml.txt) is a fix for it. Could you please apply it and try? I tried it and there seems to be no runtime diff. I will add this fix in a release tomorrow. :D

> Could you please let me know the input parameters (including the test case) where a pop-up page like below will appear?

```
java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar \
-p /home/<my user name>/IdeaProjects/collector-sahab-experiments \
-l e5d67a8 \
-r 9c2d18b38dd7df29612bb9888c59d8cf262a7977 \
-c  Math-2/src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java \
--slug ASSERT-KTH/collector-sahab-experiments
```
> `collector-sahab-experiments` refer to https://github.com/ASSERT-KTH/collector-sahab-experiments.
> Patch source: https://github.com/ASSERT-KTH/collector-sahab-experiments/commit/9c2d18b38dd7df29612bb9888c59d8cf262a7977

**Comment by Sunhui26yeah** [comment]
Thank you so much, Aman! I will try to figure it out and give it a try. Hope you have a good night!

**Comment by Sunhui26yeah** [comment]
Hi Aman,

Sorry to disturb you again. I tried both the v0.5.4-SNAPSHOT(after fixing by you) and v0.5.3 with the target repository you provided.
"java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar \
-p /home/\<my user name\>/IdeaProjects/collector-sahab-experiments \
-l e5d67a8 \
-r 9c2d18b38dd7df29612bb9888c59d8cf262a7977 \
-c  Math-2/src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java \
--slug ASSERT-KTH/collector-sahab-experiments"

I wonder have you face this problem before? 'pom.xml does not exist in /tmp/collector-sahab-experiments_e5d67a8xxxxxx/left'
**_The parameters I entered into the terminal were copied directly._**
![de42c69813471ce318297e5269ea42f](https://github.com/user-attachments/assets/75965a68-8332-45a9-8e8e-4d2f2404c804)
![d23ff9ca162450360852505c2719854](https://github.com/user-attachments/assets/6cb5d3af-622d-4a89-981b-ffac5be66fc2)

I also cannot find 'pom.xml' within the 'left' folder.
![5f1811fdecd51d95192a664448f799f](https://github.com/user-attachments/assets/29f32b71-843b-4c0d-b970-027c0a9a6420)

**_I tried to run collector_sahab on my own test maven repository, there are three questions raised._**
![df4d2bceba60600df178c3e3acc7d8d](https://github.com/user-attachments/assets/70604275-c872-47af-9f7e-19005b8b6168)

The generated html is below
![7dae8eeab4df6b2970939fc50ce98d2](https://github.com/user-attachments/assets/b69f6f90-b029-4f36-9769-8359b1913490)
Thank you for taking the time to reply to me amidst your busy schedule!

**Comment by Sunhui26yeah** [comment]
Update:

![image](https://github.com/user-attachments/assets/da3122d0-47bd-4e95-a2f2-d634aa4fde47)
The 'pom.xml' file can be found in the 'Math2' folder. I wonder if I am missing something?

**Comment by algomaster99** [comment]
Hi! Sorry took so long to respond.

> "java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar
-p /home/<my user name>/IdeaProjects/collector-sahab-experiments
-l e5d67a8
-r 9c2d18b38dd7df29612bb9888c59d8cf262a7977
-c Math-2/src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java
--slug ASSERT-KTH/collector-sahab-experiments"

Sorry, I accidentally sent you the wrong paths. It should be:

```diff
 java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar
- -p /home/<my user name>/IdeaProjects/collector-sahab-experiments
+ -p /home/<my user name>/IdeaProjects/collector-sahab-experiments/Math2
 -l e5d67a8
 -r 9c2d18b38dd7df29612bb9888c59d8cf262a7977
- -c Math-2/src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java
+ /src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java
  --slug ASSERT-KTH/collector-sahab-experiments"
```

Upon running this command, I get a trace of around 3.0 GB which then fails at comparison so you still don't get the augmented diff, sadly. For this use case, I added a flag `--selected-tests` that runs only specific tests in order to minimise the trace. The selected tests are the ones that you are sure that will cover the patch. You can run the following command and try it out for yourself. 

```
java -jar main/target/collector-sahab-0.5.4-SNAPSHOT-jar-with-dependencies.jar \                                                ✔  at 20:46:39 
-p /home/aman/Desktop/experiments/collector-sahab-experiments/Math-2 \
-l e5d67a8 \
-r 9c2d18b \
-c src/main/java/org/apache/commons/math3/distribution/AbstractIntegerDistribution.java \
--slug ASSERT-KTH/collector-sahab-experiments --selected-tests org.apache.commons.math3.distribution.HypergeometricDistributionTest::testMath1021
```

The diff you will see in output.html - 
![image](https://github.com/user-attachments/assets/8c4494d2-403a-41f5-9490-fd83e83c57a8)



For patches in https://github.com/ASSERT-KTH/collector-sahab-experiments, the corresponding `--selected-tests` are given [here](https://github.com/ASSERT-KTH/collector-sahab-experiments/tree/master/projects-metadata). For example, for the above case [`patch1-Math-2-Arja-plausible`](https://github.com/ASSERT-KTH/collector-sahab-experiments/compare/patch1-Math-2-Arja-plausible), you need to look for `bug id 2` which is [here](https://github.com/ASSERT-KTH/collector-sahab-experiments/blob/5939a781d7d7757d34920296c78566c9abe301ae/projects-metadata/Math-metadata.csv#L3).

**Comment by Sunhui26yeah** [comment]
Sorry for the late reply! It took me some time to finally resolve some issues on my end. I successfully ran both the case you gave me and the one I produced myself. I really appreciate your help during this process and look forward to talking with you tomorrow. I have listed all the issues I encountered for future reference, both for myself and others.

1. One common issue is that some plugins fail to download and need to be downloaded individually.
2. The maven repository we want to generate run-time diffs has to include Junit test class(Which I didn't realize at that time.)
3. Java JDK version needs to be 11. 
4. Warnings from SL4J are fine.
5. Warnings from confliction between CDP version and Selenium are fine.

Thank you so much for your valuable help!

**Comment by algomaster99** [comment]
Happy that I could help 😊 

> One common issue is that some plugins fail to download and need to be downloaded individually.

Do you mean maven plugins? Could you tell which one was failing to download?

> The maven repository we want to generate run-time diffs has to include Junit test class(Which I didn't realize at that time.)

Yes, that's the core assumption of the paper. 

> Java JDK version needs to be 11.

This depends upon the projects you are computing diff for. Later JDKs won't support code that are compiled to earlier versions of Java. For example, JDK 22 won't support classfiles compiled to 6. But they would support later versions. Anyway, the minimum version you need to run collector-sahab is 11.

> Warnings from SL4J are fine.

Do you want to help proposing a fix for it? :) it's a very common warning. See how to resolve it - https://www.slf4j.org/codes.html#noProviders.
 > Warnings from confliction between CDP version and Selenium are fine.

I have never investigated this so maybe it's fine 😅
